name: webauthn
description: A plugin implementing the WebAuthn authenticator model for generating Public Key Credentials
version: 0.2.1
homepage:
repository: https://github.com/flutter-institute/webauthn
issue_tracker: https://github.com/flutter-institute/webauthn/issues
platforms:
  android:
  ios:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^1.5.0
  byte_extensions: ^0.0.3
  cbor: ^6.1.1
  collection: ^1.17.2
  crypto: ^3.0.3
  crypto_keys: ^0.3.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  hex: ^0.2.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.7
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.1.4
  local_auth_windows: ^1.0.10
  logger: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  precis: ^0.0.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.3
  mockito: ^5.3.2
  sqflite_common_ffi: ^2.1.1+1

flutter:
